In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
 !pip install tensorflow

In [4]:
from tensorflow.keras.layers import Dense #NN

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

In [6]:
data = load_iris()
features = data['data']
target = data['target']

In [7]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
targets_ = to_categorical(target, num_classes=3)

In [9]:
targets_

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [10]:
features.shape[1]

4

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, targets_)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train)

In [12]:
model = Sequential()

model.add(Dense(100, input_shape=(features.shape[1],)))
model.add(Dense(30, activation="relu"))
# model.add(Dense(45, activation="relu"))
# model.add(Dense(32, activation="relu"))
# model.add(Dense(23, activation="relu"))
model.add(Dense(3, activation="softmax"))

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 30)                3030      
                                                                 
 dense_2 (Dense)             (None, 3)                 93        
                                                                 
Total params: 3,623
Trainable params: 3,623
Non-trainable params: 0
_________________________________________________________________


In [14]:
import tensorflow

model.compile(optimizer="sgd", 
              loss=tensorflow.keras.losses.CategoricalCrossentropy(), 
              metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val))

Epoch 1/50
3/3 [==============================] - 1s 96ms/step - loss: 1.5586 - accuracy: 0.2500 - val_loss: 1.1174 - val_accuracy: 0.3214
Epoch 2/50
3/3 [==============================] - 0s 11ms/step - loss: 1.1211 - accuracy: 0.4167 - val_loss: 1.0537 - val_accuracy: 0.3214
Epoch 3/50
3/3 [==============================] - 0s 12ms/step - loss: 1.0530 - accuracy: 0.3452 - val_loss: 1.0189 - val_accuracy: 0.6786
Epoch 4/50
3/3 [==============================] - 0s 14ms/step - loss: 1.0108 - accuracy: 0.5714 - val_loss: 0.9470 - val_accuracy: 0.6786
Epoch 5/50
3/3 [==============================] - 0s 12ms/step - loss: 0.9482 - accuracy: 0.6667 - val_loss: 0.9093 - val_accuracy: 0.6786
Epoch 6/50
3/3 [==============================] - 0s 14ms/step - loss: 0.8962 - accuracy: 0.6667 - val_loss: 0.8877 - val_accuracy: 0.3571
Epoch 7/50
3/3 [==============================] - 0s 14ms/step - loss: 0.8628 - accuracy: 0.6071 - val_loss: 0.8389 - val_accuracy: 0.6786
Epoch 8/50
3/3 [===========

In [16]:
X_train.shape

(84, 4)

In [17]:
y_train.shape

(84, 3)

In [23]:
y_pred = model.predict(X_test)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [24]:
y_pred

array([[0.9033899 , 0.0873907 , 0.00921948],
       [0.9555282 , 0.0401418 , 0.00432999],
       [0.0053393 , 0.39395493, 0.6007058 ],
       [0.07001889, 0.6158636 , 0.31411758],
       [0.04490031, 0.58227855, 0.37282106],
       [0.08726252, 0.62297726, 0.28976026],
       [0.0010098 , 0.33925155, 0.6597387 ],
       [0.00421508, 0.4875413 , 0.5082436 ],
       [0.0141829 , 0.5155792 , 0.4702379 ],
       [0.00546614, 0.50801915, 0.48651472],
       [0.00466819, 0.35053003, 0.6448018 ],
       [0.06489778, 0.6523266 , 0.2827757 ],
       [0.00982687, 0.60463995, 0.38553324],
       [0.00423689, 0.4729381 , 0.52282506],
       [0.20493516, 0.5739176 , 0.22114718],
       [0.01474015, 0.5155404 , 0.46971944],
       [0.03143275, 0.6709356 , 0.2976317 ],
       [0.01719139, 0.5008289 , 0.48197973],
       [0.9167617 , 0.07660444, 0.00663376],
       [0.8888165 , 0.10192615, 0.00925736],
       [0.06531963, 0.6669118 , 0.26776856],
       [0.94230837, 0.05306594, 0.00462568],
       [0.

In [ ]:
# preprocessing code

In [25]:
model.save("NN.h5")

In [26]:
from tensorflow.keras.models import load_model

In [27]:
model = load_model("./NN.h5")

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 30)                3030      
                                                                 
 dense_2 (Dense)             (None, 3)                 93        
                                                                 
Total params: 3,623
Trainable params: 3,623
Non-trainable params: 0
_________________________________________________________________


In [29]:
clas = model.predict([[0.9, 0.8, 0.5, 0.9]])

1/1 [==============================] - 0s 72ms/step


In [30]:
clas

array([[0.33863625, 0.29071176, 0.370652  ]], dtype=float32)

In [32]:
np.argmax(clas)

2

In [31]:
classes = ['iris satosa', 'virginica', 'iris color']

classes[np.argmax(clas)]

'iris color'